### PR TITLE
Implement a multicast filtering api and enable v6 for lwip

### LINKED ISSUE #18: IPv6 support (multicast and MAC address filtering)
To be able to properly implement IPv6, a way to enable/disable filtering for specific multicast mac addresses is required.
A way to set the `allmulti` flag is a viable workaround, but is not currently available in the library.

https://github.com/georgerobotics/cyw43-driver/blob/195dfcc10bb6f379e3dea45147590db2203d3c7b/src/cyw43_ll.c#L1859

For more details on my journey to enable IPv6 in the Arduino core so far, see earlephilhower/arduino-pico#732.
In particular, the [`multicast.diff` spoiler in this comment contains my hack to enable the `allmulti` flag](https://github.com/earlephilhower/arduino-pico/pull/732#issuecomment-1202990025). The code is not of PR quality, but could serve as inspiration for what the bare minimum required work to enable IPv6 would be.

Ideally we'd unfilter specific MACs, but I didn't find any references to such functionality in this repo, and I haven't found any documentation for the firmware.

### PR DESCRIPTION
**Pull request by felixdoerre**
This is related to #19 should resolve #18.
Thanks to the good hint in from @peterharperuk  https://github.com/georgerobotics/cyw43-driver/issues/18#issuecomment-1225913653 I was able to use the mac address filtering. With these changes applied, ipv6 works perfectly for me.
And hints? Should I split up the 2 commits into to separate PRs?

### CODE REVIEW

**Comment by felixdoerre** [comment]
I've rebased my PR onto #25 (hence @jimmo's commit is now in the history). So This PR now depends on #25.

**Comment by peterharperuk** [comment]
There are a couple of other changes I'd like with these IPV6 changes, pushed on here https://github.com/peterharperuk/cyw43-driver/commits/ipv6

**Comment by felixdoerre** [comment]
perfect, thank you. I've just tested the changed version on my board and it works perfectly. Should I now fast-forward this PR to include your changes or how do we get them merged?

**Comment by peterharperuk** [comment]
It might be nice if you can pull all the changes into this one merge request and reference this issue https://github.com/georgerobotics/cyw43-driver/issues/18?
It's up to Damien to merge but we would like this in the next pico sdk release.

**Comment by felixdoerre** [comment]
Now that #25 is merged, I've rebased this PR onto the current master. @dpgeorge, would you mind reviewing and merging this as well?

**Comment by dpgeorge** [comment]
Thanks for rebasing, this looks good.  I will do some very minor code style fixes during merge.

**Pull request merged**
